image: alpine:3.8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - deploy

before_script:
  - apk add --updte nodejs nodejs-npm python python-dev py-pip build-base
  - pip install awscli
  - pip install aws-sam-cli

deploy_acceptance:
  variables:
    AWS_ACCESS_KEY_ID: $_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $_AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $_AWS_DEFAULT_REGION
    STAGE: acc
    BUCKET_NAME: express-app-sam-namik
  stage: deploy
  script:
   - npm install
   - sam package --template-file template.yaml --output-template-file my-express-app.yaml --s3-bucket $BUCKET_NAME
   - sam deploy --template-file my-express-app.yaml --stack-name $STAGE --capabilities CAPABILITY_IAM


deploy_prod:
  variables:
    AWS_ACCESS_KEY_ID: $_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $_AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $_AWS_DEFAULT_REGION
    STAGE: prod
    BUCKET_NAME: express-app-sam-namik
  stage: deploy
  script:
   - npm install
   - sam package --template-file template.yaml --output-template-file my-express-app.yaml --s3-bucket $BUCKET_NAME
   - sam deploy --template-file my-express-app.yaml --stack-name $STAGE --capabilities CAPABILITY_IAM
  when: manual
  only:
    - master
  allow_failure: false
